# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='vk_groip_id',
            field=models.CharField(default=1, max_length=100, verbose_name='vk group id'),
            preserve_default=False,
        ),
    ]
