# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-06 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smm', '0002_group_vk_groip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
